version: '3' 
services:
  webstorm-docker:
    image: openkbs/webstorm-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webstorm-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - .env
#    ports:
#      - 8080:8080
    volumes:
      - ./workspace:/home/developer/workspace

